version: '2'

services:
  postgres:
    restart: always
    container_name: pg_companies
    image: postgres
    environment:
      - PGDATA=/data/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=companies
    volumes:
      - ./env/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - db

  app:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.app
    container_name: company_catalog_app
    environment:
      - POSTGRES_CONNECTION_URL=postgres://postgres:12345678@pg_companies:5432/companies
    ports:
      - "8080:8080"
    networks:
      - db

networks:
  db:
    driver: bridge